# Generated by Django 4.2.11 on 2024-05-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('name', models.CharField(db_column='SUBJECT_NAME', max_length=25)),
                ('age', models.IntegerField(db_column='SUBJECT_AGE')),
                ('birth', models.DateField(db_column='SUBJECT_BIRTH')),
                ('sex', models.CharField(choices=[(1, 'man'), (2, 'woman')], db_column='SUBJECT_SEX', max_length=10)),
            ],
            options={
                'db_table': 'OC_USER',
                'ordering': ['id'],
                'unique_together': {('name', 'age', 'birth')},
            },
        ),
    ]
