# Generated by Django 4.2.11 on 2025-01-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eeg', '0002_eeg_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='EEGDiff1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('topography_delta', models.ImageField(db_column='EEG_TOPOGRAPHY_DELTA', upload_to='')),
                ('topography_theta', models.ImageField(db_column='EEG_TOPOGRAPHY_THETA', upload_to='')),
                ('topography_alpha', models.ImageField(db_column='EEG_TOPOGRAPHY_ALPHA', upload_to='')),
                ('topography_beta', models.ImageField(db_column='EEG_TOPOGRAPHY_BETA', upload_to='')),
                ('topography_gamma', models.ImageField(db_column='EEG_TOPOGRAPHY_GAMMA', upload_to='')),
                ('connectivity_delta', models.ImageField(db_column='EEG_CONNECTIVITY_DELTA', upload_to='')),
                ('connectivity_theta', models.ImageField(db_column='EEG_CONNECTIVITY_THETA', upload_to='')),
                ('connectivity_alpha', models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA', upload_to='')),
                ('connectivity_beta', models.ImageField(db_column='EEG_CONNECTIVITY_BETA', upload_to='')),
                ('connectivity_gamma', models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA', upload_to='')),
            ],
            options={
                'db_table': 'OC_EEG_DIFF_1',
            },
        ),
        migrations.CreateModel(
            name='EEGDiff2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('topography_delta', models.ImageField(db_column='EEG_TOPOGRAPHY_DELTA', upload_to='')),
                ('topography_theta', models.ImageField(db_column='EEG_TOPOGRAPHY_THETA', upload_to='')),
                ('topography_alpha', models.ImageField(db_column='EEG_TOPOGRAPHY_ALPHA', upload_to='')),
                ('topography_beta', models.ImageField(db_column='EEG_TOPOGRAPHY_BETA', upload_to='')),
                ('topography_gamma', models.ImageField(db_column='EEG_TOPOGRAPHY_GAMMA', upload_to='')),
                ('connectivity_delta', models.ImageField(db_column='EEG_CONNECTIVITY_DELTA', upload_to='')),
                ('connectivity_theta', models.ImageField(db_column='EEG_CONNECTIVITY_THETA', upload_to='')),
                ('connectivity_alpha', models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA', upload_to='')),
                ('connectivity_beta', models.ImageField(db_column='EEG_CONNECTIVITY_BETA', upload_to='')),
                ('connectivity_gamma', models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA', upload_to='')),
            ],
            options={
                'db_table': 'OC_EEG_DIFF_2',
            },
        ),
        migrations.CreateModel(
            name='EEGDiff3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('topography_delta', models.ImageField(db_column='EEG_TOPOGRAPHY_DELTA', upload_to='')),
                ('topography_theta', models.ImageField(db_column='EEG_TOPOGRAPHY_THETA', upload_to='')),
                ('topography_alpha', models.ImageField(db_column='EEG_TOPOGRAPHY_ALPHA', upload_to='')),
                ('topography_beta', models.ImageField(db_column='EEG_TOPOGRAPHY_BETA', upload_to='')),
                ('topography_gamma', models.ImageField(db_column='EEG_TOPOGRAPHY_GAMMA', upload_to='')),
                ('connectivity_delta', models.ImageField(db_column='EEG_CONNECTIVITY_DELTA', upload_to='')),
                ('connectivity_theta', models.ImageField(db_column='EEG_CONNECTIVITY_THETA', upload_to='')),
                ('connectivity_alpha', models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA', upload_to='')),
                ('connectivity_beta', models.ImageField(db_column='EEG_CONNECTIVITY_BETA', upload_to='')),
                ('connectivity_gamma', models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA', upload_to='')),
            ],
            options={
                'db_table': 'OC_EEG_DIFF_3',
            },
        ),
        migrations.CreateModel(
            name='EEGDiff4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('topography_delta', models.ImageField(db_column='EEG_TOPOGRAPHY_DELTA', upload_to='')),
                ('topography_theta', models.ImageField(db_column='EEG_TOPOGRAPHY_THETA', upload_to='')),
                ('topography_alpha', models.ImageField(db_column='EEG_TOPOGRAPHY_ALPHA', upload_to='')),
                ('topography_beta', models.ImageField(db_column='EEG_TOPOGRAPHY_BETA', upload_to='')),
                ('topography_gamma', models.ImageField(db_column='EEG_TOPOGRAPHY_GAMMA', upload_to='')),
                ('connectivity_delta', models.ImageField(db_column='EEG_CONNECTIVITY_DELTA', upload_to='')),
                ('connectivity_theta', models.ImageField(db_column='EEG_CONNECTIVITY_THETA', upload_to='')),
                ('connectivity_alpha', models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA', upload_to='')),
                ('connectivity_beta', models.ImageField(db_column='EEG_CONNECTIVITY_BETA', upload_to='')),
                ('connectivity_gamma', models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA', upload_to='')),
            ],
            options={
                'db_table': 'OC_EEG_DIFF_4',
            },
        ),
        migrations.AddField(
            model_name='eeg',
            name='diff1',
            field=models.ForeignKey(db_column='EEG_DIFF_1_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eeg', to='eeg.eegdiff1'),
        ),
        migrations.AddField(
            model_name='eeg',
            name='diff2',
            field=models.ForeignKey(db_column='EEG_DIFF_2_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eeg', to='eeg.eegdiff2'),
        ),
        migrations.AddField(
            model_name='eeg',
            name='diff3',
            field=models.ForeignKey(db_column='EEG_DIFF_3_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eeg', to='eeg.eegdiff3'),
        ),
        migrations.AddField(
            model_name='eeg',
            name='diff4',
            field=models.ForeignKey(db_column='EEG_DIFF_4_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eeg', to='eeg.eegdiff4'),
        ),
    ]
