# Generated by Django 4.2.11 on 2025-01-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg', '0003_eegdiff1_eegdiff2_eegdiff3_eegdiff4_eeg_diff1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eegbaseline',
            name='connectivity_alpha2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegbaseline',
            name='connectivity_beta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegbaseline',
            name='connectivity_delta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegbaseline',
            name='connectivity_gamma2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegbaseline',
            name='connectivity_theta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_alpha2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_beta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_delta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_gamma2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_theta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_alpha2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_beta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_delta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_gamma2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_theta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_alpha2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_beta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_delta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_gamma2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_theta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_alpha2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_beta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_delta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_gamma2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_theta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery1',
            name='connectivity_alpha2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery1',
            name='connectivity_beta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery1',
            name='connectivity_delta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery1',
            name='connectivity_gamma2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery1',
            name='connectivity_theta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery2',
            name='connectivity_alpha2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery2',
            name='connectivity_beta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery2',
            name='connectivity_delta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery2',
            name='connectivity_gamma2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery2',
            name='connectivity_theta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation1',
            name='connectivity_alpha2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation1',
            name='connectivity_beta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation1',
            name='connectivity_delta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation1',
            name='connectivity_gamma2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation1',
            name='connectivity_theta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation2',
            name='connectivity_alpha2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation2',
            name='connectivity_beta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation2',
            name='connectivity_delta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation2',
            name='connectivity_gamma2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation2',
            name='connectivity_theta2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_PLV', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegbaseline',
            name='connectivity_alpha',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegbaseline',
            name='connectivity_beta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_BETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegbaseline',
            name='connectivity_delta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_DELTA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegbaseline',
            name='connectivity_gamma',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegbaseline',
            name='connectivity_theta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_THETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff1',
            name='connectivity_alpha',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff1',
            name='connectivity_beta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_BETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff1',
            name='connectivity_delta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_DELTA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff1',
            name='connectivity_gamma',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff1',
            name='connectivity_theta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_THETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff2',
            name='connectivity_alpha',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff2',
            name='connectivity_beta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_BETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff2',
            name='connectivity_delta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_DELTA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff2',
            name='connectivity_gamma',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff2',
            name='connectivity_theta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_THETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff3',
            name='connectivity_alpha',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff3',
            name='connectivity_beta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_BETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff3',
            name='connectivity_delta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_DELTA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff3',
            name='connectivity_gamma',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff3',
            name='connectivity_theta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_THETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff4',
            name='connectivity_alpha',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff4',
            name='connectivity_beta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_BETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff4',
            name='connectivity_delta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_DELTA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff4',
            name='connectivity_gamma',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegdiff4',
            name='connectivity_theta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_THETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegrecovery1',
            name='connectivity_alpha',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegrecovery1',
            name='connectivity_beta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_BETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegrecovery1',
            name='connectivity_delta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_DELTA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegrecovery1',
            name='connectivity_gamma',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegrecovery1',
            name='connectivity_theta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_THETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegrecovery2',
            name='connectivity_alpha',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegrecovery2',
            name='connectivity_beta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_BETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegrecovery2',
            name='connectivity_delta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_DELTA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegrecovery2',
            name='connectivity_gamma',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegrecovery2',
            name='connectivity_theta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_THETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegstimulation1',
            name='connectivity_alpha',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegstimulation1',
            name='connectivity_beta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_BETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegstimulation1',
            name='connectivity_delta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_DELTA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegstimulation1',
            name='connectivity_gamma',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegstimulation1',
            name='connectivity_theta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_THETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegstimulation2',
            name='connectivity_alpha',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_ALPHA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegstimulation2',
            name='connectivity_beta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_BETA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegstimulation2',
            name='connectivity_delta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_DELTA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegstimulation2',
            name='connectivity_gamma',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_GAMMA_COH', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegstimulation2',
            name='connectivity_theta',
            field=models.ImageField(db_column='EEG_CONNECTIVITY_THETA_COH', upload_to=''),
        ),
    ]
