# Generated by Django 4.2.11 on 2025-08-27 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eeg', '0005_rename_connectivity_alpha2_eegbaseline_connectivity2_alpha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EEGFAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('delta', models.ImageField(db_column='EEG_FRONTAL_ASYMMETRY_DELTA', upload_to='')),
                ('theta', models.ImageField(db_column='EEG_FRONTAL_ASYMMETRY_THETA', upload_to='')),
                ('alpha', models.ImageField(db_column='EEG_FRONTAL_ASYMMETRY_ALPHA', upload_to='')),
                ('beta', models.ImageField(db_column='EEG_FRONTAL_ASYMMETRY_BETA', upload_to='')),
                ('gamma', models.ImageField(db_column='EEG_FRONTAL_ASYMMETRY_GAMMA', upload_to='')),
            ],
            options={
                'db_table': 'OC_EEG_FAA',
            },
        ),
        migrations.AddField(
            model_name='eeg',
            name='faa',
            field=models.ForeignKey(
                to='eeg.eegfaa',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='eeg',
                db_column='EEG_FAA_ID',
            ),
        ),
    ]
