# Generated by Django 4.2.11 on 2024-07-04 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRVBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('sdnn', models.FloatField(blank=True, db_column='HRV_SDNN', null=True)),
                ('rmssd', models.FloatField(blank=True, db_column='HRV_RMSSD', null=True)),
                ('sdsd', models.FloatField(blank=True, db_column='HRV_SDSD', null=True)),
                ('nn50', models.FloatField(blank=True, db_column='HRV_NN50', null=True)),
                ('pnn50', models.FloatField(blank=True, db_column='HRV_pNN50', null=True)),
                ('tri_index', models.FloatField(blank=True, db_column='HRV_TRI_Index', null=True)),
                ('vlf_rel_power', models.FloatField(blank=True, db_column='HRV_REL_VLF', null=True)),
                ('lf_rel_power', models.FloatField(blank=True, db_column='HRV_REL_LF', null=True)),
                ('hf_rel_power', models.FloatField(blank=True, db_column='HRV_REF_HF', null=True)),
                ('lh_ratio', models.FloatField(blank=True, db_column='HRV_LH_RATIO', null=True)),
                ('norm_lf', models.FloatField(blank=True, db_column='HRV_NORM_LF', null=True)),
                ('norm_hf', models.FloatField(blank=True, db_column='HRV_NORM_HF', null=True)),
                ('psd', models.JSONField(db_column='HRV_PSD')),
                ('heart_rate', models.ImageField(db_column='HRV_HEAD_RATE', upload_to='')),
                ('comparison', models.ImageField(db_column='HRV_COMPARISON', upload_to='')),
            ],
            options={
                'db_table': 'OC_HRV_BASELINE',
            },
        ),
        migrations.CreateModel(
            name='HRVRecovery1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('sdnn', models.FloatField(blank=True, db_column='HRV_SDNN', null=True)),
                ('rmssd', models.FloatField(blank=True, db_column='HRV_RMSSD', null=True)),
                ('sdsd', models.FloatField(blank=True, db_column='HRV_SDSD', null=True)),
                ('nn50', models.FloatField(blank=True, db_column='HRV_NN50', null=True)),
                ('pnn50', models.FloatField(blank=True, db_column='HRV_pNN50', null=True)),
                ('tri_index', models.FloatField(blank=True, db_column='HRV_TRI_Index', null=True)),
                ('vlf_rel_power', models.FloatField(blank=True, db_column='HRV_REL_VLF', null=True)),
                ('lf_rel_power', models.FloatField(blank=True, db_column='HRV_REL_LF', null=True)),
                ('hf_rel_power', models.FloatField(blank=True, db_column='HRV_REF_HF', null=True)),
                ('lh_ratio', models.FloatField(blank=True, db_column='HRV_LH_RATIO', null=True)),
                ('norm_lf', models.FloatField(blank=True, db_column='HRV_NORM_LF', null=True)),
                ('norm_hf', models.FloatField(blank=True, db_column='HRV_NORM_HF', null=True)),
                ('psd', models.JSONField(db_column='HRV_PSD')),
                ('heart_rate', models.ImageField(db_column='HRV_HEAD_RATE', upload_to='')),
                ('comparison', models.ImageField(db_column='HRV_COMPARISON', upload_to='')),
            ],
            options={
                'db_table': 'OC_HRV_RECOVERY_1',
            },
        ),
        migrations.CreateModel(
            name='HRVRecovery2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('sdnn', models.FloatField(blank=True, db_column='HRV_SDNN', null=True)),
                ('rmssd', models.FloatField(blank=True, db_column='HRV_RMSSD', null=True)),
                ('sdsd', models.FloatField(blank=True, db_column='HRV_SDSD', null=True)),
                ('nn50', models.FloatField(blank=True, db_column='HRV_NN50', null=True)),
                ('pnn50', models.FloatField(blank=True, db_column='HRV_pNN50', null=True)),
                ('tri_index', models.FloatField(blank=True, db_column='HRV_TRI_Index', null=True)),
                ('vlf_rel_power', models.FloatField(blank=True, db_column='HRV_REL_VLF', null=True)),
                ('lf_rel_power', models.FloatField(blank=True, db_column='HRV_REL_LF', null=True)),
                ('hf_rel_power', models.FloatField(blank=True, db_column='HRV_REF_HF', null=True)),
                ('lh_ratio', models.FloatField(blank=True, db_column='HRV_LH_RATIO', null=True)),
                ('norm_lf', models.FloatField(blank=True, db_column='HRV_NORM_LF', null=True)),
                ('norm_hf', models.FloatField(blank=True, db_column='HRV_NORM_HF', null=True)),
                ('psd', models.JSONField(db_column='HRV_PSD')),
                ('heart_rate', models.ImageField(db_column='HRV_HEAD_RATE', upload_to='')),
                ('comparison', models.ImageField(db_column='HRV_COMPARISON', upload_to='')),
            ],
            options={
                'db_table': 'OC_HRV_RECOVERY_2',
            },
        ),
        migrations.CreateModel(
            name='HRVStimulation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('sdnn', models.FloatField(blank=True, db_column='HRV_SDNN', null=True)),
                ('rmssd', models.FloatField(blank=True, db_column='HRV_RMSSD', null=True)),
                ('sdsd', models.FloatField(blank=True, db_column='HRV_SDSD', null=True)),
                ('nn50', models.FloatField(blank=True, db_column='HRV_NN50', null=True)),
                ('pnn50', models.FloatField(blank=True, db_column='HRV_pNN50', null=True)),
                ('tri_index', models.FloatField(blank=True, db_column='HRV_TRI_Index', null=True)),
                ('vlf_rel_power', models.FloatField(blank=True, db_column='HRV_REL_VLF', null=True)),
                ('lf_rel_power', models.FloatField(blank=True, db_column='HRV_REL_LF', null=True)),
                ('hf_rel_power', models.FloatField(blank=True, db_column='HRV_REF_HF', null=True)),
                ('lh_ratio', models.FloatField(blank=True, db_column='HRV_LH_RATIO', null=True)),
                ('norm_lf', models.FloatField(blank=True, db_column='HRV_NORM_LF', null=True)),
                ('norm_hf', models.FloatField(blank=True, db_column='HRV_NORM_HF', null=True)),
                ('psd', models.JSONField(db_column='HRV_PSD')),
                ('heart_rate', models.ImageField(db_column='HRV_HEAD_RATE', upload_to='')),
                ('comparison', models.ImageField(db_column='HRV_COMPARISON', upload_to='')),
            ],
            options={
                'db_table': 'OC_HRV_STIMULATION_1',
            },
        ),
        migrations.CreateModel(
            name='HRVStimulation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('sdnn', models.FloatField(blank=True, db_column='HRV_SDNN', null=True)),
                ('rmssd', models.FloatField(blank=True, db_column='HRV_RMSSD', null=True)),
                ('sdsd', models.FloatField(blank=True, db_column='HRV_SDSD', null=True)),
                ('nn50', models.FloatField(blank=True, db_column='HRV_NN50', null=True)),
                ('pnn50', models.FloatField(blank=True, db_column='HRV_pNN50', null=True)),
                ('tri_index', models.FloatField(blank=True, db_column='HRV_TRI_Index', null=True)),
                ('vlf_rel_power', models.FloatField(blank=True, db_column='HRV_REL_VLF', null=True)),
                ('lf_rel_power', models.FloatField(blank=True, db_column='HRV_REL_LF', null=True)),
                ('hf_rel_power', models.FloatField(blank=True, db_column='HRV_REF_HF', null=True)),
                ('lh_ratio', models.FloatField(blank=True, db_column='HRV_LH_RATIO', null=True)),
                ('norm_lf', models.FloatField(blank=True, db_column='HRV_NORM_LF', null=True)),
                ('norm_hf', models.FloatField(blank=True, db_column='HRV_NORM_HF', null=True)),
                ('psd', models.JSONField(db_column='HRV_PSD')),
                ('heart_rate', models.ImageField(db_column='HRV_HEAD_RATE', upload_to='')),
                ('comparison', models.ImageField(db_column='HRV_COMPARISON', upload_to='')),
            ],
            options={
                'db_table': 'OC_HRV_STIMULATION_2',
            },
        ),
        migrations.CreateModel(
            name='HRV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('nni', models.JSONField(db_column='HRV_NNI', null=True)),
                ('rmssd', models.JSONField(db_column='HRV_RMSSD', null=True)),
                ('baseline', models.ForeignKey(db_column='HRV_BASELINE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrv', to='ecg.hrvbaseline')),
                ('recovery1', models.ForeignKey(db_column='HRV_RECOVERY_1_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrv', to='ecg.hrvrecovery1')),
                ('recovery2', models.ForeignKey(db_column='HRV_RECOVERY_2_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrv', to='ecg.hrvrecovery2')),
                ('stimulation1', models.ForeignKey(db_column='HRV_STIMULATION_1_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrv', to='ecg.hrvstimulation1')),
                ('stimulation2', models.ForeignKey(db_column='HRV_STIMULATION_2_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrv', to='ecg.hrvstimulation2')),
            ],
            options={
                'db_table': 'OC_HRV',
            },
        ),
    ]
