# Generated by Django 4.2.11 on 2024-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrv',
            name='measurement_date',
            field=models.DateTimeField(blank=True, db_column='MEASUREMENT_DATE', null=True),
        ),
    ]
