# Generated by Django 4.2.11 on 2025-01-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('irls', models.IntegerField(blank=True, db_column='IRLS', null=True)),
                ('psql', models.IntegerField(blank=True, db_column='PSQL', null=True)),
                ('isi', models.IntegerField(blank=True, db_column='ISI', null=True)),
                ('ess', models.IntegerField(blank=True, db_column='ESS', null=True)),
                ('compass31', models.FloatField(blank=True, db_column='COMPASS31', null=True)),
                ('bai', models.IntegerField(blank=True, db_column='BAI', null=True)),
                ('bdi2', models.IntegerField(blank=True, db_column='BDI2', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
