# Generated by Django 4.2.11 on 2025-01-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_questionnaire_note'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionnaire',
            table='OC_QUESTIONNAIRE',
        ),
    ]
